### ISSUE TITLE
Handle errors more gracefully

### ISSUE THREAD

**Issue by fregante** [DrewML/chrome-webstore-upload-cli#105]
Known errors should be parsed and displayed more cleanly

### Now

```
Response code 400 (Bad Request)
{
    "error": {
        "errors": [
            {
                "domain": "global",
                "reason": "badRequest",
                "message": "Publish condition not met: To publish your item, you must provide mandatory privacy information in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole. Click on your item from the home page and enter this information on the Privacy tab."
            }
        ],
        "code": 400,
        "message": "Publish condition not met: To publish your item, you must provide mandatory privacy information in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole. Click on your item from the home page and enter this information on the Privacy tab."
    }
}
```

### Ideal

```
Publish condition not met: To publish your item, you must provide mandatory privacy information in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole. Click on your item from the home page and enter this information on the Privacy tab.
```

## `invalid_grant`

https://github.com/DrewML/chrome-webstore-upload-cli/issues/36

### Now

```
Response code 400 (Bad Request)
{
    "error": "invalid_grant",
    "error_description": "Bad Request"
}
```

### Ideal

```
Response code 400 (Bad Request)
invalid_grant: Bad Request
Probably the supplied keys are invalid. Make sure to trim any extra spaces.
```

**Comment by fregante** [comment]
- https://github.com/fregante/chrome-webstore-upload-cli/issues/93

```
npm warn exec The following package was not found and will be installed: chrome-webstore-upload-cli@3.4.0
Fetching token...
Uploading extension...
Error: Not Found
    at throwIfNotOk (file:///home/runner/.npm/_npx/x/node_modules/chrome-webstore-upload/index.js:20:23)
    at APIClient.uploadExisting (file:///home/runner/.npm/_npx/x/node_modules/chrome-webstore-upload/index.js:61:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async doAutoPublish (file:///home/runner/.npm/_npx/x/node_modules/chrome-webstore-upload-cli/cli.js:73:28)
    at async init (file:///home/runner/.npm/_npx/x/node_modules/chrome-webstore-upload-cli/cli.js:171:9)
    at async file:///home/runner/.npm/_npx/x/node_modules/chrome-webstore-upload-cli/cli.js:180:5 {
  response: { error: { code: 404, message: 'Not Found', errors: [Array] } }
```

**Comment by fregante** [comment]
Should be completed. Errors are no longer shown with a stack trace and they're always followed by two links. Locking so that new improvement request are made in new issues.
