### ISSUE TITLE
Syntax Error?

### ISSUE THREAD

**Issue by saiichihashimoto** [DrewML/chrome-webstore-upload-cli#11]
No matter how I run this thing, I get a syntax error:

```
const { green, red } = require('chalk');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

**Comment by DrewML** [comment]
Hey @saiichihashimoto,

Looks like you're running a version of node that isn't supported by this package. The [minimum npm version](https://github.com/DrewML/chrome-webstore-upload-cli#minimum-nodejs-version) is specified in the docs.

**Comment by DrewML** [comment]
If you need to use this on an older version of node, it's likely possible using the `babel-node` CLI provided by the Babel project.

**Comment by saiichihashimoto** [comment]
My node version is v4.1.2
